use_frameworks!

target 'HMAMessageViewManager_Example' do
  pod 'HMAMessageViewManager', :path => '../'
end

target 'HMAMessageViewManager_Tests' do
    pod 'HMAMessageViewManager', :path => '../'
end

