language: objective-c
osx_image: xcode9.2
# before_install:
    # - brew update
    # - brew install xctool
script:
    - pod --version
    - xcodebuild -showsdks
    - cd Example
    - pod install
    - xcrun simctl list
    - xcodebuild clean build test -workspace HMAMessageViewManager.xcworkspace -scheme HMAMessageViewManager-Tests -sdk iphonesimulator11.2 -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2" ONLY_ACTIVE_ARCH=NO

notifications:
  email:
    recipients:
      - jki@jki.lv
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
